### ISSUE TITLE
if url has #

### ISSUE THREAD

**Issue by cn-src** [maddouri/IntelliJ-OnlineSearch#1]
if url has #, how to use it.
like this 'http://search.maven.org/#search|ga|1|guice'.

**Comment by maddouri** [comment]
Thank you for reporting the issue.

Currently ([1.1.0](https://github.com/maddouri/IntelliJ-OnlineSearch/tree/1.1.0)), the "[search query placeholder](https://github.com/maddouri/IntelliJ-OnlineSearch/blob/1.1.0/src/io/github/maddouri/intellij/OnlineSearch/state/PluginSettings.java#L43)" is set to `#` for all search engines.

As you have noticed, this does cause a problem if the search engine's URL contains the same sub-string.

How about I add a 3rd text field next to the search engine's URL in which the users can specify a custom query placeholder ?

**EDIT:** Here is a preview of the `1.1.1` fix:

![onlinesearch-1 1 1-preview](https://cloud.githubusercontent.com/assets/4390935/14590558/f97d6778-04fd-11e6-84a6-6a8f4f2e2189.png)

I think that this should get rid of the problem once and for all. (It is always possible to find a string that doesn't exist in the base URL and define it as the query placeholder) The update should be present in Jetbrains' repo very soon.

**Comment by maddouri** [comment]
[Problem solved in 1.1.1](https://github.com/maddouri/IntelliJ-OnlineSearch/releases/tag/1.1.1)
